name: Java CI with Gradle

on:
  push:
    branches:
      - develop
      - feature/lab2
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
